// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('quizteszt', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1552, height: 840 })
    await driver.findElement(By.css(".bi")).click()
    await driver.findElement(By.css(".logout")).click()
    await driver.findElement(By.css(".login")).click()
    await driver.findElement(By.css(".input-group:nth-child(1) > input")).click()
    await driver.findElement(By.css(".input-group:nth-child(1) > input")).sendKeys("admin")
    await driver.findElement(By.css(".input-group:nth-child(2) > input")).click()
    await driver.findElement(By.css(".input-group:nth-child(2) > input")).sendKeys("Admin123!")
    await driver.findElement(By.css(".bejelentkezese")).click()
    await driver.findElement(By.css(".lucide")).click()
    await driver.findElement(By.linkText("Quiz")).click()
    await driver.findElement(By.css(".btn:nth-child(2)")).click()
    await driver.findElement(By.css(".btn:nth-child(3)")).click()
    await driver.findElement(By.css(".btn:nth-child(3)")).click()
    await driver.findElement(By.css(".btn:nth-child(2)")).click()
    await driver.findElement(By.css(".btn:nth-child(2)")).click()
    await driver.findElement(By.css(".btn:nth-child(4)")).click()
    await driver.findElement(By.css(".btn:nth-child(2)")).click()
    await driver.findElement(By.css(".btn:nth-child(3)")).click()
    await driver.findElement(By.css(".btn:nth-child(1)")).click()
    await driver.findElement(By.css(".btn:nth-child(1)")).click()
    await driver.findElement(By.css(".btn:nth-child(3)")).click()
    await driver.findElement(By.css(".bi-person-circle")).click()
    await driver.findElement(By.linkText("Kérdések")).click()
    await driver.findElement(By.css("tr:nth-child(1) .btn-outline-primary")).click()
    await driver.findElement(By.css(".btn-outline-primary")).click()
    await driver.findElement(By.css(".card:nth-child(3) > .row .form-control")).click()
    await driver.findElement(By.css(".card:nth-child(3) > .row .form-control")).sendKeys("Orbán viktor")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css(".bi-person-circle")).click()
    await driver.findElement(By.linkText("Felhasználók")).click()
    await driver.findElement(By.css(".list-group-item:nth-child(2) > .d-flex")).click()
    await driver.findElement(By.css(".btn-outline-danger")).click()
    assert(await driver.switchTo().alert().getText() == "Biztosan törölni szeretné ezt a felhasználót?")
    await driver.switchTo().alert().accept()
  })
})
